### ISSUE TITLE
M215 pairing error 1: device timeout

### ISSUE THREAD

**Issue by jmeinke** [Lekensteyn/ltunify#2]
Hey @Lekensteyn ,
my M215 behaves strangely in the last month. While being paired, sometimes the mouse pointer just does not move anymore while it was working perfectly well for 1 hour or more before. Now, I tried to unpair it and pair it again. However, unfortunately, pairing fails.

Here's the output of `ltunify` related commands:
```
% ltunify -d /dev/hidraw0 list                                                                                                                                                                                 
Devices count: 0
Connected devices:
```

```
% ltunify receiver-info
Serial number: 00000000
Firmware version: 024.001.00023
Bootloader version: BL.001.008
```

```
% ltunify pair
Please turn your wireless device off and on to start pairing.
Pairing result: Timeout (1)
```
Solaar does not achieve to pair the mouse either, see https://github.com/pwr-Solaar/Solaar/issues/560

I've replaced the battery one week ago...
Is my mouse broken? Thanks for your advice!

**Comment by Lekensteyn** [comment]
Let's continue the conversation in https://github.com/pwr-Solaar/Solaar/issues/560
